# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eCXsVoFChoTDp0LVAflSOqMdy_VoAe7x
"""

#1.Importing necessary libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

#2.loading the datset
iris=load_iris()
X=iris.data   # Input features
y=iris.target #target Labels

#3.splitting into training and testing(80%-traaining,20%-testing)
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

#4.Building the model & training the data
model=LogisticRegression(max_iter=200)
model.fit(x_train,y_train)

#5.Making predictions
y_pred=model.predict(x_test)

#6.Calculating the accuracy with the original & Predicted
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)